namespace RovOverlay.Desktop.Services;

// Ending a game from the score, the calmer Control Panel, and Home showing what is live.
public sealed partial class Loc
{
    private static readonly Dictionary<string, string> FlowEn = new()
    {
        ["Flow.AddPoint"] = "+1",
        ["Flow.AddPointName"] = "+1 {0}",
        ["Flow.AddPointTip"] = "This side won the game: gives it the point, records the winner, keeps the draft with that game and puts the next game on the board. A wrong press is fixed with the round arrow and the score box.",
        ["Flow.RemovePoint"] = "−1",
        ["Flow.RemovePointName"] = "-1 {0}",
        ["Flow.RemovePointTip"] = "Take back the last game this side won: the point comes off, that game's winner is cleared, and the game goes back on the board with its draft and sides. If that point ended the series, the series opens again. Greyed out when the score is 0.",
        ["Flow.GameUndone"] = "{0}'s point taken back · game {1} is on the board again",
        ["Flow.SeriesReopened"] = "{0}'s point taken back · the series is open again at game {1}",
        ["Flow.Err.NoPoints"] = "This team has no point to take back.",
        ["Flow.Err.NotLast"] = "The other team won the last game. Take that point back first.",
        ["Flow.NextGame"] = "{0} won the game · game {1} is on the board",
        ["Flow.SeriesOver"] = "SERIES OVER",
        ["Flow.SeriesWon"] = "{0} win the series {1}–{2}",
        ["Flow.Next"] = "Next: {0} vs {1}",
        ["Flow.PutOnAir"] = "Put on air",
        ["Flow.NoNext"] = "No other match in this tournament is ready yet",
        ["Flow.Err.GameDecided"] = "This game already has a winner. Use the round arrow to move on.",
        ["Flow.Err.SeriesOver"] = "This series is already over.",
        ["Flow.Err.RoundLimit"] = "There are no more rounds.",
        ["Flow.Err.NotRecorded"] = "The point could not be recorded for this match, so nothing was changed. Check the score boxes.",
        ["Flow.Err.RoundFirst"] = "Already on round 1.",
        ["Hotkeys.BluePlus"] = "+1 blue side",
        ["Hotkeys.BluePlusNote"] = "The team on the blue side won the game, the same as +1 beside the blue score.",
        ["Hotkeys.RedPlus"] = "+1 red side",
        ["Hotkeys.RedPlusNote"] = "The team on the red side won the game, the same as +1 beside the red score.",
        ["Hotkeys.BlueMinus"] = "−1 blue side",
        ["Hotkeys.BlueMinusNote"] = "Takes a point back from the team on the blue side now, the same as −1 beside the blue score. Teams swap sides after each game, so the team that just won is usually on red by then.",
        ["Hotkeys.RedMinus"] = "−1 red side",
        ["Hotkeys.RedMinusNote"] = "Takes a point back from the team on the red side now, the same as −1 beside the red score. Teams swap sides after each game, so the team that just won is usually on blue by then.",
        ["Hotkeys.PrevRound"] = "Previous round",
        ["Hotkeys.NextRound"] = "Next round",
        ["Hotkeys.RoundNote"] = "The same as the round arrows on the Control Panel.",
        ["Flow.SwapSides"] = "Swap sides each game",
        ["Flow.SwapSidesTip"] = "When the round changes, the two teams swap sides: team A is blue in games 1, 3 and 5, and red in games 2 and 4. Each team keeps its own score and draft. Switch this off if the teams choose their own side.",
        ["Flow.TeamSetup"] = "Team setup",
        ["Flow.TeamSetupTip"] = "Names, logos, nicknames and lanes. Folds away by itself when the draft starts, so the picks have the room.",

        ["Home.OnAirNow"] = "ON AIR NOW",
        ["Home.QuickMatch"] = "Quick match, not part of a tournament",
        ["Home.GoToControl"] = "Go to Control",
        ["Home.OpenBracket"] = "Open bracket",
        ["Home.ReadyToPlay"] = "READY TO PLAY",
        ["Home.NoReady"] = "Nothing is waiting. Matches show up here once a tournament has its bracket drawn.",
        ["Home.ReadyTip"] = "Put on air and go to the Control Panel"
    };

    private static readonly Dictionary<string, string> FlowTh = new()
    {
        ["Flow.AddPoint"] = "+1",
        ["Flow.AddPointName"] = "+1 {0}",
        ["Flow.AddPointTip"] = "ฝั่งนี้ชนะเกมนี้: ให้แต้ม บันทึกผู้ชนะ เก็บดราฟต์ไว้กับเกมนี้ แล้วขึ้นเกมถัดไปบนกระดาน กดผิดแก้ได้ด้วยลูกศรรอบกับช่องคะแนน",
        ["Flow.RemovePoint"] = "−1",
        ["Flow.RemovePointName"] = "-1 {0}",
        ["Flow.RemovePointTip"] = "ถอนเกมล่าสุดที่ฝั่งนี้ชนะ: แต้มถูกหักออก ผู้ชนะของเกมนั้นถูกล้าง แล้วเกมนั้นกลับขึ้นกระดานพร้อมดราฟต์และฝั่งเดิม ถ้าแต้มนั้นเคยปิดซีรีส์ ซีรีส์จะกลับมาแข่งต่อ กดไม่ได้เมื่อคะแนนเป็น 0",
        ["Flow.GameUndone"] = "ถอนแต้มของ {0} แล้ว · เกมที่ {1} กลับขึ้นกระดาน",
        ["Flow.SeriesReopened"] = "ถอนแต้มของ {0} แล้ว · ซีรีส์กลับมาแข่งต่อที่เกมที่ {1}",
        ["Flow.Err.NoPoints"] = "ทีมนี้ยังไม่มีแต้มให้ถอน",
        ["Flow.Err.NotLast"] = "อีกทีมชนะเกมล่าสุด ถอนแต้มของทีมนั้นก่อน",
        ["Flow.NextGame"] = "{0} ชนะเกมนี้ · เกมที่ {1} ขึ้นกระดานแล้ว",
        ["Flow.SeriesOver"] = "ซีรีส์จบแล้ว",
        ["Flow.SeriesWon"] = "{0} ชนะซีรีส์ {1}–{2}",
        ["Flow.Next"] = "คู่ถัดไป: {0} พบ {1}",
        ["Flow.PutOnAir"] = "ขึ้นจอ",
        ["Flow.NoNext"] = "ยังไม่มีคู่อื่นในทัวร์นาเมนต์นี้ที่พร้อมเล่น",
        ["Flow.Err.GameDecided"] = "เกมนี้มีผู้ชนะแล้ว ใช้ลูกศรรอบเพื่อไปเกมถัดไป",
        ["Flow.Err.SeriesOver"] = "ซีรีส์นี้จบไปแล้ว",
        ["Flow.Err.RoundLimit"] = "ไม่มีรอบถัดไปแล้ว",
        ["Flow.Err.NotRecorded"] = "บันทึกแต้มลงแมตช์นี้ไม่สำเร็จ จึงไม่มีอะไรเปลี่ยน ลองดูช่องคะแนนอีกครั้ง",
        ["Flow.Err.RoundFirst"] = "อยู่รอบที่ 1 แล้ว",
        ["Hotkeys.BluePlus"] = "+1 ฝั่งน้ำเงิน",
        ["Hotkeys.BluePlusNote"] = "ทีมที่อยู่ฝั่งน้ำเงินชนะเกมนี้ เหมือนกด +1 ข้างคะแนนฝั่งน้ำเงิน",
        ["Hotkeys.RedPlus"] = "+1 ฝั่งแดง",
        ["Hotkeys.RedPlusNote"] = "ทีมที่อยู่ฝั่งแดงชนะเกมนี้ เหมือนกด +1 ข้างคะแนนฝั่งแดง",
        ["Hotkeys.BlueMinus"] = "−1 ฝั่งน้ำเงิน",
        ["Hotkeys.BlueMinusNote"] = "ถอนแต้มของทีมที่อยู่ฝั่งน้ำเงินตอนนี้ เหมือนกด −1 ข้างคะแนนฝั่งน้ำเงิน ทีมสลับฝั่งกันหลังจบแต่ละเกม ทีมที่เพิ่งชนะจึงมักอยู่ฝั่งแดงแล้ว",
        ["Hotkeys.RedMinus"] = "−1 ฝั่งแดง",
        ["Hotkeys.RedMinusNote"] = "ถอนแต้มของทีมที่อยู่ฝั่งแดงตอนนี้ เหมือนกด −1 ข้างคะแนนฝั่งแดง ทีมสลับฝั่งกันหลังจบแต่ละเกม ทีมที่เพิ่งชนะจึงมักอยู่ฝั่งน้ำเงินแล้ว",
        ["Hotkeys.PrevRound"] = "รอบก่อนหน้า",
        ["Hotkeys.NextRound"] = "รอบถัดไป",
        ["Hotkeys.RoundNote"] = "เหมือนกดลูกศรรอบบนหน้าคุมงาน",
        ["Flow.SwapSides"] = "สลับฝั่งทุกเกม",
        ["Flow.SwapSidesTip"] = "เมื่อเปลี่ยนรอบ สองทีมจะสลับฝั่งกันเอง ทีม A อยู่ฝั่งน้ำเงินในเกมที่ 1, 3, 5 และฝั่งแดงในเกมที่ 2, 4 แต้มและดราฟต์ของแต่ละทีมตามทีมไปด้วย ปิดไว้ถ้าให้ทีมเลือกฝั่งเอง",
        ["Flow.TeamSetup"] = "ตั้งค่าทีม",
        ["Flow.TeamSetupTip"] = "ชื่อทีม โลโก้ ชื่อผู้เล่น และเลน พับเก็บเองเมื่อเริ่มดราฟต์ ช่องพิคจะได้มีที่",

        ["Home.OnAirNow"] = "กำลังออกอากาศ",
        ["Home.QuickMatch"] = "แมตช์เดี่ยว ไม่ได้อยู่ในทัวร์นาเมนต์",
        ["Home.GoToControl"] = "ไปหน้าคุมงาน",
        ["Home.OpenBracket"] = "เปิดสายการแข่ง",
        ["Home.ReadyToPlay"] = "พร้อมเล่น",
        ["Home.NoReady"] = "ยังไม่มีคู่ที่รออยู่ คู่แข่งจะมาแสดงตรงนี้เมื่อทัวร์นาเมนต์จับสายแล้ว",
        ["Home.ReadyTip"] = "ขึ้นจอแล้วไปหน้าคุมงาน"
    };
}
