namespace RovOverlay.Desktop.Services;

// Control Panel strings. Thai follows v2's wording where v2 had the same label.
public sealed partial class Loc
{
    private static readonly Dictionary<string, string> ControlEn = new()
    {
        ["Control.Tournament"] = "Tournament",
        ["Control.MatchTitle"] = "Match title",
        ["Control.AutoSaves"] = "Auto-saves",
        ["Control.Saved"] = "Saved",
        ["Control.Size"] = "SIZE",
        ["Control.Size1080Tip"] = "Set every overlay and result screen to 1920 × 1080",
        ["Control.Size1440Tip"] = "Set every overlay and result screen to 2560 × 1440",
        ["Control.Banner"] = "BANNER",
        ["Control.Show"] = "Show",
        ["Control.Hide"] = "Hide",
        ["Control.OnAir"] = "ON AIR",

        ["Control.BlueTeam"] = "BLUE TEAM",
        ["Control.RedTeam"] = "RED TEAM",
        ["Control.Score"] = "SCORE",
        ["Control.TeamName"] = "Team name",
        ["Control.FromRegistry"] = "From registry",
        ["Control.FromRegistryTip"] = "Fill this side from a saved team: name, logo and roster",
        ["Control.Upload"] = "Upload logo",
        ["Control.ClearLogo"] = "Clear logo",
        ["Control.LogoHint"] = "Square PNG, JPG or WEBP. Drawn at 184 × 184 on 1440p, so 184px or larger stays sharp.",
        ["Control.TeamLoaded"] = "Team loaded",
        ["Control.Nickname"] = "NICKNAME",
        ["Control.Lane"] = "LANE",
        ["Control.HeroPick"] = "HERO PICK",
        ["Control.Ban"] = "BANS",
        ["Control.PickN"] = "Pick {0}",
        ["Control.BanN"] = "Ban {0}",
        ["Control.Swap"] = "SW",
        ["Control.ConfirmPick"] = "CONFIRM",
        ["Control.ConfirmPickTip"] = "The overlay is showing this hero already, quietly. Confirm to lock it in: that is when the pick sound and the animation play, and when the draft moves on.",
        ["Control.Cancel"] = "✕",
        ["Control.SwapPlayerTip"] = "Swap this nickname with another row: press here, then on the other row",
        ["Control.SwapPickTip"] = "Swap this pick with another row: press here, then on the other row",
        ["Control.ClearSlot"] = "clear",
        ["Control.PlayerSwapped"] = "Player {0} swapped with {1}",
        ["Control.PickSwapped"] = "Pick {0} swapped with {1}",
        ["Control.HeroNotFound"] = "No hero by that name",
        ["Control.HeroTaken"] = "{0} is already used",

        ["Control.DraftTimer"] = "DRAFT TIMER",
        ["Control.Ready"] = "READY",
        ["Control.Done"] = "Done",
        ["Control.Running"] = "Running",
        ["Control.Paused"] = "Paused",
        ["Control.PhaseN"] = "Phase {0} / {1}",
        ["Control.Start"] = "START",
        ["Control.ResetDraft"] = "RESET",
        ["Control.Prev"] = "PREV",
        ["Control.Pause"] = "PAUSE",
        ["Control.Resume"] = "RESUME",
        ["Control.Next"] = "NEXT",
        ["Control.Round"] = "ROUND",
        ["Control.RoundsOnBoard"] = "{0} on the board",
        ["Control.PrevRoundTip"] = "Go back to the previous round and put its draft back on the board",
        ["Control.NextRoundTip"] = "File this draft as a previous round and start the next one",

        ["Control.Sound"] = "SOUND EFFECTS",
        ["Control.SoundNote"] = "Levels reach the overlay straight away. TEST plays here, not on stream.",
        ["Control.Test"] = "TEST",

        ["Control.Undo"] = "UNDO",
        ["Control.SwitchTeams"] = "SWITCH TEAMS",
        ["Control.TeamsSwitched"] = "Teams switched",
        ["Control.ResetMatch"] = "RESET MATCH",
        ["Control.ResetTitle"] = "Reset match",
        ["Control.ResetBody"] = "Reset the whole match? Team names, players, score, picks and bans all go back to empty. This cannot be undone.",
        ["Control.Reset"] = "Reset",
        ["Control.ResetDone"] = "Match reset",
        ["Control.ClearPicksBans"] = "CLEAR PICKS & BANS",
        ["Control.ClearTitle"] = "Clear picks and bans",
        ["Control.ClearBody"] = "Clear every pick and ban for both teams? Team names, players and score are kept. This cannot be undone.",
        ["Control.Clear"] = "Clear",
        ["Control.Cleared"] = "All picks and bans cleared",

        ["Control.HintConfirm"] = "confirm hero",
        ["Control.HintEscape"] = "leave box",
        ["Control.HintBanner"] = "show/hide overlay",
        ["Control.HintPause"] = "pause",
        ["Control.HintPrev"] = "prev phase",
        ["Control.HintNext"] = "next phase",
        ["Control.HintUndo"] = "undo",
        ["Keys.Tap"] = "Tap {0}",

        ["Sfx.pick"] = "Pick",
        ["Sfx.pick.note"] = "when a hero is picked",
        ["Sfx.ban"] = "Ban",
        ["Sfx.ban.note"] = "when a hero is banned",
        ["Sfx.timer"] = "Timer",
        ["Sfx.timer.note"] = "each of the last ten seconds",
        ["Sfx.Missing"] = "No {0} sound file found"
    };

    private static readonly Dictionary<string, string> ControlTh = new()
    {
        ["Control.Tournament"] = "ทัวร์นาเมนต์",
        ["Control.MatchTitle"] = "ชื่อแมตช์",
        ["Control.AutoSaves"] = "บันทึกอัตโนมัติ",
        ["Control.Saved"] = "บันทึกแล้ว",
        ["Control.Size"] = "ขนาด",
        ["Control.Size1080Tip"] = "ตั้งทุก overlay และหน้าผลเป็น 1920 × 1080",
        ["Control.Size1440Tip"] = "ตั้งทุก overlay และหน้าผลเป็น 2560 × 1440",
        ["Control.Banner"] = "แบนเนอร์",
        ["Control.Show"] = "แสดง",
        ["Control.Hide"] = "ซ่อน",
        ["Control.OnAir"] = "ออนแอร์",

        ["Control.BlueTeam"] = "ทีมน้ำเงิน",
        ["Control.RedTeam"] = "ทีมแดง",
        ["Control.Score"] = "คะแนน",
        ["Control.TeamName"] = "ชื่อทีม",
        ["Control.FromRegistry"] = "ดึงจากทะเบียน",
        ["Control.FromRegistryTip"] = "เติมฝั่งนี้จากทีมในทะเบียน ทั้งชื่อ โลโก้ และรายชื่อผู้เล่น",
        ["Control.Upload"] = "อัปโหลดโลโก้",
        ["Control.ClearLogo"] = "ลบโลโก้",
        ["Control.LogoHint"] = "ไฟล์ PNG, JPG หรือ WEBP ทรงจัตุรัส วาดที่ 184 × 184 บนจอ 1440p ขนาด 184px ขึ้นไปจึงจะคมทั้งสองขนาด",
        ["Control.TeamLoaded"] = "โหลดทีมแล้ว",
        ["Control.Nickname"] = "ชื่อในเกม",
        ["Control.Lane"] = "เลน",
        ["Control.HeroPick"] = "ฮีโร่ที่พิค",
        ["Control.Ban"] = "แบน",
        ["Control.PickN"] = "พิค {0}",
        ["Control.BanN"] = "แบน {0}",
        ["Control.Swap"] = "สลับ",
        ["Control.ConfirmPick"] = "ยืนยัน",
        ["Control.ConfirmPickTip"] = "ตอนนี้ overlay ขึ้นภาพฮีโร่ตัวนี้ให้แล้วแบบเงียบ ๆ กดยืนยันเพื่อล็อก เสียงพิคกับอนิเมชันจะเล่นตอนนั้น และดราฟต์ถึงจะเดินต่อ",
        ["Control.Cancel"] = "✕",
        ["Control.SwapPlayerTip"] = "สลับชื่อผู้เล่นกับอีกแถว กดปุ่มนี้ แล้วไปกดที่แถวที่ต้องการ",
        ["Control.SwapPickTip"] = "สลับฮีโร่ที่พิคกับอีกแถว กดปุ่มนี้ แล้วไปกดที่แถวที่ต้องการ",
        ["Control.ClearSlot"] = "ล้าง",
        ["Control.PlayerSwapped"] = "สลับผู้เล่น {0} กับ {1} แล้ว",
        ["Control.PickSwapped"] = "สลับพิค {0} กับ {1} แล้ว",
        ["Control.HeroNotFound"] = "ไม่มีฮีโร่ชื่อนี้",
        ["Control.HeroTaken"] = "{0} ถูกใช้ไปแล้ว",

        ["Control.DraftTimer"] = "นาฬิกาดราฟต์",
        ["Control.Ready"] = "พร้อม",
        ["Control.Done"] = "จบแล้ว",
        ["Control.Running"] = "กำลังเดิน",
        ["Control.Paused"] = "หยุดพักไว้",
        ["Control.PhaseN"] = "เฟส {0} / {1}",
        ["Control.Start"] = "เริ่ม",
        ["Control.ResetDraft"] = "รีเซ็ต",
        ["Control.Prev"] = "ก่อนหน้า",
        ["Control.Pause"] = "พัก",
        ["Control.Resume"] = "ไปต่อ",
        ["Control.Next"] = "ถัดไป",
        ["Control.Round"] = "รอบ",
        ["Control.RoundsOnBoard"] = "บนกระดานแล้ว {0}",
        ["Control.PrevRoundTip"] = "ย้อนไปรอบก่อนหน้า แล้วเอาดราฟต์ของรอบนั้นกลับขึ้นกระดาน",
        ["Control.NextRoundTip"] = "เก็บดราฟต์นี้เป็นรอบก่อนหน้า แล้วเริ่มรอบใหม่",

        ["Control.Sound"] = "เสียงเอฟเฟกต์",
        ["Control.SoundNote"] = "ระดับเสียงถึง overlay ทันที ปุ่มทดสอบดังที่เครื่องนี้ ไม่ออกอากาศ",
        ["Control.Test"] = "ทดสอบ",

        ["Control.Undo"] = "ย้อนกลับ",
        ["Control.SwitchTeams"] = "สลับสองฝั่ง",
        ["Control.TeamsSwitched"] = "สลับสองฝั่งแล้ว",
        ["Control.ResetMatch"] = "ล้างแมตช์",
        ["Control.ResetTitle"] = "ล้างแมตช์",
        ["Control.ResetBody"] = "ล้างทั้งแมตช์ใช่ไหม ชื่อทีม ผู้เล่น คะแนน พิคและแบน จะกลับไปเป็นค่าว่างทั้งหมด ย้อนกลับไม่ได้",
        ["Control.Reset"] = "ล้าง",
        ["Control.ResetDone"] = "ล้างแมตช์แล้ว",
        ["Control.ClearPicksBans"] = "ล้างพิคและแบน",
        ["Control.ClearTitle"] = "ล้างพิคและแบน",
        ["Control.ClearBody"] = "ล้างพิคและแบนของทั้งสองทีมใช่ไหม ชื่อทีม ผู้เล่น และคะแนนยังอยู่ ย้อนกลับไม่ได้",
        ["Control.Clear"] = "ล้าง",
        ["Control.Cleared"] = "ล้างพิคและแบนทั้งหมดแล้ว",

        ["Control.HintConfirm"] = "ยืนยันฮีโร่",
        ["Control.HintEscape"] = "ออกจากช่อง",
        ["Control.HintBanner"] = "แสดง/ซ่อนแบนเนอร์",
        ["Control.HintPause"] = "พัก",
        ["Control.HintPrev"] = "เฟสก่อนหน้า",
        ["Control.HintNext"] = "เฟสถัดไป",
        ["Control.HintUndo"] = "ย้อนกลับ",
        ["Keys.Tap"] = "แตะ {0}",

        ["Sfx.pick"] = "พิค",
        ["Sfx.pick.note"] = "ตอนที่ฮีโร่ถูกพิค",
        ["Sfx.ban"] = "แบน",
        ["Sfx.ban.note"] = "ตอนที่ฮีโร่ถูกแบน",
        ["Sfx.timer"] = "นาฬิกา",
        ["Sfx.timer.note"] = "ทุกวินาทีในสิบวินาทีสุดท้าย",
        ["Sfx.Missing"] = "ไม่พบไฟล์เสียง {0}"
    };
}
