namespace RovOverlay.Desktop.Services;

// Bracket, pick/ban history and analytics strings.
public sealed partial class Loc
{
    private static readonly Dictionary<string, string> M4En = new()
    {
        ["Bracket.Bye"] = "bye",
        ["Bracket.Teams"] = "{0} teams",
        ["Bracket.Hint"] = "Press the arrow on a match to put it on air. Type in the score boxes to record a result.",
        ["Bracket.NeedTeams"] = "Add at least two teams on the tournament page, then draw the bracket here.",
        ["Bracket.NothingDrawn"] = "No matches drawn yet. Use Draw matches above to build the bracket.",
        ["Bracket.Draw"] = "Draw matches",
        ["Bracket.DrawTip"] = "Build the bracket from the teams entered",
        ["Bracket.DrawAgain"] = "Draw again",
        ["Bracket.DrawAgainTip"] = "Replace the current bracket and every score on it",
        ["Bracket.DrawAgainBody"] = "The current bracket and every score recorded on it are replaced. This cannot be undone.",
        ["Bracket.DrawnSeed"] = "Matches drawn by seed",
        ["Bracket.DrawnRandom"] = "Matches drawn at random",
        ["Bracket.Random"] = "Random draw",
        ["Bracket.RandomTip"] = "Ignore seeds and pair the teams at random",
        ["Bracket.Clear"] = "Clear",
        ["Bracket.ClearTitle"] = "Clear the bracket",
        ["Bracket.ClearBody"] = "Every match and score is removed. The teams stay in the tournament.",
        ["Bracket.Cleared"] = "Bracket cleared",
        ["Bracket.OnAir"] = "Game {0} is on air",
        ["Bracket.OnAirTip"] = "Put this match on air and point the draft at it",
        ["Bracket.Winners"] = "Winners bracket",
        ["Bracket.Losers"] = "Losers bracket",
        ["Bracket.Playoff"] = "Playoff",
        ["Bracket.Final"] = "Final",
        ["Bracket.Semis"] = "Semifinals",
        ["Bracket.Quarters"] = "Quarterfinals",
        ["Bracket.Reset"] = "Reset (if needed)",

        ["Drafts.Title"] = "RECORDED DRAFTS",
        ["Drafts.Count"] = "{0} games",
        ["Drafts.CountOne"] = "1 game",
        ["Drafts.Shown"] = "{0} of {1} games",
        ["Drafts.None"] = "No draft has been recorded in this tournament yet.",
        ["Drafts.NoMatch"] = "Nothing matches that filter.",
        ["Drafts.AllTeams"] = "All teams",
        ["Drafts.FindHero"] = "Find a hero",
        ["Drafts.ClearFilters"] = "Clear filters",
        ["Drafts.GameN"] = "GAME {0}",
        ["Drafts.Pick"] = "PICK",
        ["Drafts.Ban"] = "BAN",

        ["Analytics.Title"] = "Pick & ban analytics",
        ["Analytics.Games"] = "{0} games",
        ["Analytics.GamesOne"] = "1 game",
        ["Analytics.HeroesSeen"] = "{0} heroes seen",
        ["Analytics.Decided"] = "{0} with a winner",
        ["Analytics.Search"] = "Find a hero",
        ["Analytics.Tournament"] = "Tournament",
        ["Analytics.Team"] = "Team",
        ["Analytics.AllTournaments"] = "All tournaments",
        ["Analytics.AllTeams"] = "All teams",
        ["Analytics.AllGames"] = "All games",
        ["Analytics.Hero"] = "HERO",
        ["Analytics.Presence"] = "PRESENCE",
        ["Analytics.Pick"] = "PICK",
        ["Analytics.Ban"] = "BAN",
        ["Analytics.Win"] = "WIN",
        ["Analytics.BanPrio"] = "BAN PRIO",
        ["Analytics.Empty"] = "No completed drafts yet. Play a match from a tournament and the numbers appear here.",
        ["Analytics.EmptyScope"] = "No completed drafts in this scope yet.",
        ["Analytics.NoHero"] = "No hero matches \"{0}\".",
        ["Analytics.WinTip"] = "{0} of {1} games with a recorded winner",
        ["Analytics.NoWinner"] = "No winner recorded for any game this hero was picked in",
        ["Analytics.PrioTip"] = "{0} first-phase bans ({1} of games)",
        ["Analytics.LiveNote"] = "{0} picked, {1} banned — not counted until the draft is complete",
        ["Analytics.Foot"] = "Rates are per game, not per draft slot: a hero picked in 8 of 100 games shows 8%. Only games with a completed draft are counted, and the draft in progress is shown separately so it never drags the percentages around mid-game."
    };

    private static readonly Dictionary<string, string> M4Th = new()
    {
        ["Bracket.Bye"] = "บาย",
        ["Bracket.Teams"] = "{0} ทีม",
        ["Bracket.Hint"] = "กดลูกศรบนคู่ที่ต้องการเพื่อเอาขึ้นจอ กรอกคะแนนในช่องเพื่อบันทึกผล",
        ["Bracket.NeedTeams"] = "เพิ่มทีมอย่างน้อยสองทีมในหน้าทัวร์นาเมนต์ แล้วกลับมาจับสายที่นี่",
        ["Bracket.NothingDrawn"] = "ยังไม่ได้จับสาย กดปุ่มจับสายด้านบนเพื่อสร้างสายการแข่ง",
        ["Bracket.Draw"] = "จับสาย",
        ["Bracket.DrawTip"] = "สร้างสายการแข่งจากทีมที่ลงไว้",
        ["Bracket.DrawAgain"] = "จับสายใหม่",
        ["Bracket.DrawAgainTip"] = "แทนที่สายปัจจุบันและคะแนนทั้งหมดที่บันทึกไว้",
        ["Bracket.DrawAgainBody"] = "สายปัจจุบันและคะแนนทุกนัดที่บันทึกไว้จะถูกแทนที่ ย้อนกลับไม่ได้",
        ["Bracket.DrawnSeed"] = "จับสายตามลำดับวางแล้ว",
        ["Bracket.DrawnRandom"] = "จับสายแบบสุ่มแล้ว",
        ["Bracket.Random"] = "จับสายแบบสุ่ม",
        ["Bracket.RandomTip"] = "ไม่ใช้ลำดับวาง แต่สุ่มจับคู่ทีม",
        ["Bracket.Clear"] = "ล้างสาย",
        ["Bracket.ClearTitle"] = "ล้างสายการแข่ง",
        ["Bracket.ClearBody"] = "ทุกคู่และทุกคะแนนจะถูกลบ ทีมยังอยู่ในทัวร์นาเมนต์เหมือนเดิม",
        ["Bracket.Cleared"] = "ล้างสายแล้ว",
        ["Bracket.OnAir"] = "เกม {0} ขึ้นจอแล้ว",
        ["Bracket.OnAirTip"] = "เอาคู่นี้ขึ้นจอ แล้วผูกดราฟต์เข้ากับคู่นี้",
        ["Bracket.Winners"] = "สายชนะ",
        ["Bracket.Losers"] = "สายแพ้",
        ["Bracket.Playoff"] = "รอบน็อกเอาต์",
        ["Bracket.Final"] = "รอบชิงชนะเลิศ",
        ["Bracket.Semis"] = "รอบรองชนะเลิศ",
        ["Bracket.Quarters"] = "รอบก่อนรองชนะเลิศ",
        ["Bracket.Reset"] = "นัดตัดสิน (ถ้าต้องมี)",

        ["Drafts.Title"] = "ดราฟต์ที่บันทึกไว้",
        ["Drafts.Count"] = "{0} เกม",
        ["Drafts.CountOne"] = "1 เกม",
        ["Drafts.Shown"] = "{0} จาก {1} เกม",
        ["Drafts.None"] = "ทัวร์นาเมนต์นี้ยังไม่มีดราฟต์ที่บันทึกไว้",
        ["Drafts.NoMatch"] = "ไม่มีอะไรตรงกับตัวกรองนี้",
        ["Drafts.AllTeams"] = "ทุกทีม",
        ["Drafts.FindHero"] = "ค้นหาฮีโร่",
        ["Drafts.ClearFilters"] = "ล้างตัวกรอง",
        ["Drafts.GameN"] = "เกม {0}",
        ["Drafts.Pick"] = "พิค",
        ["Drafts.Ban"] = "แบน",

        ["Analytics.Title"] = "สถิติพิคและแบน",
        ["Analytics.Games"] = "{0} เกม",
        ["Analytics.GamesOne"] = "1 เกม",
        ["Analytics.HeroesSeen"] = "เห็นฮีโร่ {0} ตัว",
        ["Analytics.Decided"] = "มีผู้ชนะ {0} เกม",
        ["Analytics.Search"] = "ค้นหาฮีโร่",
        ["Analytics.Tournament"] = "ทัวร์นาเมนต์",
        ["Analytics.Team"] = "ทีม",
        ["Analytics.AllTournaments"] = "ทุกทัวร์นาเมนต์",
        ["Analytics.AllTeams"] = "ทุกทีม",
        ["Analytics.AllGames"] = "ทุกเกม",
        ["Analytics.Hero"] = "ฮีโร่",
        ["Analytics.Presence"] = "ถูกหยิบ/แบน",
        ["Analytics.Pick"] = "พิค",
        ["Analytics.Ban"] = "แบน",
        ["Analytics.Win"] = "ชนะ",
        ["Analytics.BanPrio"] = "ลำดับแบน",
        ["Analytics.Empty"] = "ยังไม่มีดราฟต์ที่จบสมบูรณ์ เล่นสักแมตช์จากทัวร์นาเมนต์แล้วตัวเลขจะขึ้นที่นี่",
        ["Analytics.EmptyScope"] = "ยังไม่มีดราฟต์ที่จบสมบูรณ์ในขอบเขตนี้",
        ["Analytics.NoHero"] = "ไม่มีฮีโร่ที่ตรงกับ \"{0}\"",
        ["Analytics.WinTip"] = "ชนะ {0} จาก {1} เกมที่มีการบันทึกผู้ชนะ",
        ["Analytics.NoWinner"] = "ยังไม่มีเกมไหนที่ฮีโร่ตัวนี้ถูกพิคแล้วบันทึกผู้ชนะไว้",
        ["Analytics.PrioTip"] = "โดนแบนในเฟสแรก {0} ครั้ง ({1} ของเกมทั้งหมด)",
        ["Analytics.LiveNote"] = "พิคแล้ว {0} แบนแล้ว {1} ยังไม่ถูกนับจนกว่าดราฟต์จะจบ",
        ["Analytics.Foot"] = "อัตราทั้งหมดคิดต่อเกม ไม่ใช่ต่อช่องดราฟต์ ฮีโร่ที่ถูกพิค 8 จาก 100 เกมจะแสดงเป็น 8% นับเฉพาะเกมที่ดราฟต์จบสมบูรณ์ ส่วนดราฟต์ที่กำลังเล่นอยู่แยกไว้ต่างหาก จะได้ไม่ทำให้เปอร์เซ็นต์แกว่งระหว่างเกม"
    };
}
