namespace RovOverlay.Desktop.Services;

// Strings for the tournament, team registry, team profile and backup screens.
// Thai follows v2's i18n.js wherever v2 had the same sentence.
public sealed partial class Loc
{
    private static readonly Dictionary<string, string> ScreensEn = new()
    {
        ["Common.Back"] = "Back",
        ["Common.Close"] = "Close",
        ["Common.Edit"] = "Edit",
        ["Common.Profile"] = "Profile",
        ["Common.Delete"] = "Delete",
        ["Common.Saved"] = "Saved",
        ["Common.Reverted"] = "Reverted to the saved values",
        ["Common.DeleteForever"] = "Delete forever",
        ["Dialog.Images"] = "Images",
        ["Dialog.Json"] = "Backup files",
        ["Col.Team"] = "Team",

        ["Pos.none"] = "Position",
        ["Pos.jungle"] = "Jungle",
        ["Pos.carry"] = "Carry",
        ["Pos.midlane"] = "Mid lane",
        ["Pos.offlane"] = "Off lane",
        ["Pos.support"] = "Support",

        ["Round.Grand"] = "Grand final",
        ["Round.GrandReset"] = "Grand final (reset)",
        ["Round.Losers"] = "Losers round {0}",
        ["Round.Main"] = "Round {0}",
        ["Round.Playoff"] = "Playoff round {0}",
        ["Round.Group"] = "Group {0} · round {1}",

        ["Team.Name"] = "Team name",
        ["Team.Tag"] = "Tag",
        ["Team.SeedLabel"] = "Seed",
        ["Team.Seed"] = "Seed {0}",
        ["Team.PlayersLabel"] = "Players",
        ["Team.Players"] = "{0} / {1} players",
        ["Team.PlayerN"] = "Player {0}",
        ["Team.Captain"] = "Captain",
        ["Team.ChooseLogo"] = "Choose logo",
        ["Team.LogoChosen"] = "Logo: {0}",
        ["Team.UploadLogo"] = "Upload logo",
        ["Team.ClearLogo"] = "Clear logo",
        ["Team.LogoHint"] = "PNG, JPG or WEBP, up to 4 MB",
        ["Team.LogoType"] = "Use a PNG, JPG or WEBP image",
        ["Team.LogoTooBig"] = "Logo must be 4 MB or smaller",
        ["Team.LogoUploaded"] = "Logo uploaded",
        ["Team.LogoCleared"] = "Logo cleared",
        ["Team.LogoFailedAfterCreate"] = "{0} created, but the logo failed: {1}",
        ["Team.NameRequired"] = "Team name is required",
        ["Team.SaveTeam"] = "Save team",
        ["Team.Saved"] = "Team saved",
        ["Team.ClearForm"] = "Clear form",
        ["Team.FormCleared"] = "Form cleared",
        ["Team.DeleteFromRegistry"] = "Delete from registry",
        ["Team.DeleteTitle"] = "Delete team",
        ["Team.DeleteQ"] = "Delete \"{0}\" from the registry?",
        ["Team.DeleteDropped"] = "It is dropped from every tournament it entered. Match history keeps the name as it was on the day.",
        ["Team.Deleted"] = "Team deleted",

        ["Tour.NotFound"] = "Tournament not found",
        ["Tour.Gone"] = "This tournament was deleted.",
        ["Tour.BestOf"] = "Best of {0}",
        ["Tour.Teams"] = "TEAMS",
        ["Tour.TeamCount"] = "{0} / {1} teams",
        ["Tour.AddTeam"] = "Add team",
        ["Tour.PickExisting"] = "Add a team already in the registry",
        ["Tour.AddToTournament"] = "Add to tournament",
        ["Tour.RegistryEmpty"] = "No teams in the registry yet",
        ["Tour.AllIn"] = "Every registered team is already in",
        ["Tour.OrCreate"] = "…OR CREATE A NEW TEAM",
        ["Tour.CreateAndAdd"] = "Create and add",
        ["Tour.TeamAdded"] = "Team added",
        ["Tour.TeamAddedNamed"] = "{0} added",
        ["Tour.InRegistryBut"] = "{0} is in the registry, but could not be added: {1}",
        ["Tour.NoTeams"] = "No teams yet. This format holds up to {0} teams.",
        ["Tour.RemoveTip"] = "Take this team out of the tournament. It stays in the registry.",
        ["Tour.RemoveTitle"] = "Remove from tournament",
        ["Tour.RemoveQ"] = "Take \"{0}\" out of this tournament?",
        ["Tour.RemoveStays"] = "The team stays in the registry.",
        ["Tour.Remove"] = "Remove",
        ["Tour.Removed"] = "Removed from tournament",

        ["Tour.MatchSession"] = "MATCH SESSION",
        ["Tour.Played"] = "{0} / {1} played",
        ["Tour.MatchesDrawn"] = "{0} matches drawn. Put one on air from here, or open the bracket to record scores.",
        ["Tour.NextMatches"] = "Ready to play",
        ["Tour.NeedTwoTeams"] = "Add at least two teams, then open the match session to draw the bracket.",
        ["Tour.NoBracket"] = "No bracket drawn yet. Open the match session to draw it.",
        ["Tour.OpenBracket"] = "Open match session",
        ["Tour.PickBanHistory"] = "Pick / ban history",

        ["Tour.Standings"] = "STANDINGS",
        ["Tour.PerGroup"] = "Teams through per group",
        ["Tour.DrawPlayoff"] = "Draw playoff",
        ["Tour.StandingsEmpty"] = "Draw the matches first, then the table fills in as results come in.",
        ["Tour.TiedHint"] = "Rows marked = are level on every measure. Settle those by your own rules before drawing the playoff.",
        ["Tour.Table"] = "Table",
        ["Tour.Group"] = "Group {0}",
        ["Tour.StillToPlay"] = "{0} still to play",
        ["Tour.PlayoffTitle"] = "Draw the playoff bracket?",
        ["Tour.PlayoffTop"] = "The top {0} of each group go through to a knockout bracket.",
        ["Tour.PlayoffSafe"] = "The group stage is not touched. Drawing again replaces the playoff, but only while none of it has been played.",
        ["Tour.Through"] = "{0} teams are through",

        ["Tour.Details"] = "TOURNAMENT DETAILS",
        ["Tour.Name"] = "Name",
        ["Tour.Status"] = "Status",
        ["Tour.Note"] = "Note",
        ["Tour.SaveChanges"] = "Save changes",
        ["Tour.Revert"] = "Revert",
        ["Tour.FormatTooSmall"] = "{0} allows {1}, this has {2}",
        ["Tour.DeleteTournament"] = "Delete tournament",
        ["Tour.DeleteTitle"] = "Delete tournament",
        ["Tour.DeleteQ"] = "Delete \"{0}\" permanently?",
        ["Tour.DeleteOnAir"] = "It is on air right now. Deleting it takes the match off the broadcast.",
        ["Tour.DeleteErases"] = "Its team list, every match in the bracket and every draft recorded under it are erased. There is no undo and nothing left behind to restore from.",
        ["Tour.DeleteTeamsStay"] = "The teams themselves stay in the registry, along with their history in other tournaments.",
        ["Tour.Deleted"] = "Deleted {0}",
        ["Tour.DeletedCounts"] = " ({0} matches and {1} drafts gone)",

        ["Tour.ObsSources"] = "OBS SOURCES FOR THIS TOURNAMENT",
        ["Tour.ObsHint"] = "These show this tournament even when another one is on air. The rest are under OBS sources in the title bar.",

        ["Teams.Title"] = "Team registry",
        ["Teams.New"] = "New team",
        ["Teams.CreateTeam"] = "Create team",
        ["Teams.Count"] = "{0} teams",
        ["Teams.Shown"] = "{0} shown",
        ["Teams.Search"] = "Team name or tag",
        ["Teams.SelectAll"] = "Select all shown",
        ["Teams.Selected"] = "{0} selected",
        ["Teams.ClearSelection"] = "Clear selection",
        ["Teams.DeleteSelected"] = "Delete selected ({0})",
        ["Teams.DeleteSelectedTitle"] = "Delete selected teams",
        ["Teams.DeleteSelectedQ"] = "Delete these teams from the registry? ({0})",
        ["Teams.DeleteSelectedDropped"] = "They are dropped from every tournament they entered. Match history keeps the names as they were on the day.",
        ["Teams.AndMore"] = " and {0} more",
        ["Teams.DeletedN"] = "{0} teams deleted",
        ["Teams.Created"] = "{0} created",
        ["Teams.InTournaments"] = "{0} tournaments",
        ["Teams.InOneTournament"] = "1 tournament",
        ["Teams.Record"] = "{0} W – {1} L",
        ["Teams.Empty"] = "No teams yet. Create one here, or from inside a tournament.",
        ["Teams.NoMatch"] = "Nothing matches \"{0}\".",
        ["Teams.Foot"] = "Teams here are shared by every tournament. Editing a roster changes the team everywhere from then on; matches already played keep the roster they were played with.",

        ["Profile.NotFound"] = "Team not found",
        ["Profile.Captain"] = "Captain: {0}",
        ["Profile.Games"] = "{0} – {1} games",
        ["Profile.NoMatchesYet"] = "No matches played yet",
        ["Profile.Edit"] = "ROSTER AND LOGO",
        ["Profile.Tournaments"] = "TOURNAMENTS",
        ["Profile.NoTournaments"] = "This team has not been added to a tournament yet.",
        ["Profile.History"] = "MATCH HISTORY",
        ["Profile.HistoryHint"] = "{0} played, newest first",
        ["Profile.HistoryEmpty"] = "No matches yet. Draw a bracket in a tournament this team has entered.",
        ["Profile.Win"] = "Win",
        ["Profile.Loss"] = "Loss",
        ["Profile.Bye"] = "Bye",
        ["Profile.InProgress"] = "In progress",
        ["Profile.NotPlayed"] = "Not played",
        ["Profile.NoOpponent"] = "no opponent",
        ["Profile.Tbd"] = "to be decided",
        ["Profile.UnknownTeam"] = "Unknown team",
        ["Profile.DeletedTeam"] = "Deleted team",
        ["Profile.Foot"] = "Editing the roster here changes the team from now on. Matches already played keep the players they were played with, so past results and pick/ban statistics stay correct.",

        ["Settings.Backup"] = "BACKUP",
        ["Backup.Hint"] = "Everything on this machine (teams, logos, brackets and every recorded draft) saved as one file you can keep somewhere else or move to another PC. v2 backups restore here too.",
        ["Backup.Save"] = "Save a backup",
        ["Backup.RestoreButton"] = "Restore…",
        ["Backup.Saved"] = "Backup saved: {0}",
        ["Backup.NotJson"] = "That file is not readable JSON",
        ["Backup.RestoreTitle"] = "Restore this backup?",
        ["Backup.WillAdd"] = "{0} teams and {1} tournaments will be added.",
        ["Backup.Contents"] = "It also holds {0} matches, {1} recorded drafts and {2} logos, and was made on {3}.",
        ["Backup.AlreadyHere"] = "Already on this machine: {0} teams, {1} tournaments.",
        ["Backup.MergeRule"] = "Anything already on this machine is kept. Records that are already here are skipped, not replaced.",
        ["Backup.Restore"] = "Restore",
        ["Backup.Restored"] = "Restored {0} teams and {1} tournaments"
    };

    private static readonly Dictionary<string, string> ScreensTh = new()
    {
        ["Common.Back"] = "กลับ",
        ["Common.Close"] = "ปิด",
        ["Common.Edit"] = "แก้ไข",
        ["Common.Profile"] = "โปรไฟล์",
        ["Common.Delete"] = "ลบ",
        ["Common.Saved"] = "บันทึกแล้ว",
        ["Common.Reverted"] = "ย้อนกลับเป็นค่าที่บันทึกไว้แล้ว",
        ["Common.DeleteForever"] = "ลบถาวร",
        ["Dialog.Images"] = "รูปภาพ",
        ["Dialog.Json"] = "ไฟล์สำรอง",
        ["Col.Team"] = "ทีม",

        ["Pos.none"] = "ตำแหน่ง",
        ["Pos.jungle"] = "จังเกิ้ล",
        ["Pos.carry"] = "แคร์รี่",
        ["Pos.midlane"] = "เลนกลาง",
        ["Pos.offlane"] = "เลนบน",
        ["Pos.support"] = "ซัพพอร์ต",

        ["Round.Grand"] = "รอบชิงชนะเลิศ",
        ["Round.GrandReset"] = "รอบชิงชนะเลิศ (นัดตัดสิน)",
        ["Round.Losers"] = "สายแพ้ รอบ {0}",
        ["Round.Main"] = "รอบ {0}",
        ["Round.Playoff"] = "น็อกเอาต์ รอบ {0}",
        ["Round.Group"] = "กลุ่ม {0} · รอบ {1}",

        ["Team.Name"] = "ชื่อทีม",
        ["Team.Tag"] = "ตัวย่อ",
        ["Team.SeedLabel"] = "ลำดับวางสาย",
        ["Team.Seed"] = "วางสาย {0}",
        ["Team.PlayersLabel"] = "ผู้เล่น",
        ["Team.Players"] = "ผู้เล่น {0} / {1}",
        ["Team.PlayerN"] = "ผู้เล่น {0}",
        ["Team.Captain"] = "กัปตัน",
        ["Team.ChooseLogo"] = "เลือกโลโก้",
        ["Team.LogoChosen"] = "โลโก้: {0}",
        ["Team.UploadLogo"] = "อัปโหลดโลโก้",
        ["Team.ClearLogo"] = "ลบโลโก้",
        ["Team.LogoHint"] = "PNG, JPG หรือ WEBP ไม่เกิน 4 MB",
        ["Team.LogoType"] = "ใช้ไฟล์ PNG, JPG หรือ WEBP",
        ["Team.LogoTooBig"] = "โลโก้ต้องไม่เกิน 4 MB",
        ["Team.LogoUploaded"] = "อัปโหลดโลโก้แล้ว",
        ["Team.LogoCleared"] = "ลบโลโก้แล้ว",
        ["Team.LogoFailedAfterCreate"] = "สร้าง {0} แล้ว แต่โลโก้ไม่สำเร็จ: {1}",
        ["Team.NameRequired"] = "ต้องใส่ชื่อทีม",
        ["Team.SaveTeam"] = "บันทึกทีม",
        ["Team.Saved"] = "บันทึกทีมแล้ว",
        ["Team.ClearForm"] = "ล้างฟอร์ม",
        ["Team.FormCleared"] = "ล้างฟอร์มแล้ว",
        ["Team.DeleteFromRegistry"] = "ลบออกจากทะเบียน",
        ["Team.DeleteTitle"] = "ลบทีม",
        ["Team.DeleteQ"] = "ลบทีม \"{0}\" ออกจากทะเบียนใช่ไหม",
        ["Team.DeleteDropped"] = "ทีมนี้จะหลุดจากทุกทัวร์นาเมนต์ที่เคยลงแข่ง ส่วนประวัติการแข่งยังเก็บชื่อ ณ วันที่ลงเล่นไว้เหมือนเดิม",
        ["Team.Deleted"] = "ลบทีมแล้ว",

        ["Tour.NotFound"] = "ไม่พบทัวร์นาเมนต์",
        ["Tour.Gone"] = "ทัวร์นาเมนต์นี้ถูกลบไปแล้ว",
        ["Tour.BestOf"] = "Bo{0}",
        ["Tour.Teams"] = "ทีม",
        ["Tour.TeamCount"] = "{0} / {1} ทีม",
        ["Tour.AddTeam"] = "เพิ่มทีม",
        ["Tour.PickExisting"] = "เลือกทีมที่มีอยู่ในทะเบียนแล้ว",
        ["Tour.AddToTournament"] = "เพิ่มเข้าทัวร์นาเมนต์",
        ["Tour.RegistryEmpty"] = "ยังไม่มีทีมในทะเบียน",
        ["Tour.AllIn"] = "ทุกทีมในทะเบียนอยู่ในรายการนี้แล้ว",
        ["Tour.OrCreate"] = "…หรือสร้างทีมใหม่",
        ["Tour.CreateAndAdd"] = "สร้างแล้วเพิ่มเลย",
        ["Tour.TeamAdded"] = "เพิ่มทีมแล้ว",
        ["Tour.TeamAddedNamed"] = "เพิ่ม {0} แล้ว",
        ["Tour.InRegistryBut"] = "{0} อยู่ในทะเบียนแล้ว แต่เพิ่มเข้ารายการไม่สำเร็จ: {1}",
        ["Tour.NoTeams"] = "ยังไม่มีทีม รูปแบบนี้รับได้ถึง {0} ทีม",
        ["Tour.RemoveTip"] = "เอาทีมนี้ออกจากทัวร์นาเมนต์ ทีมยังอยู่ในทะเบียน",
        ["Tour.RemoveTitle"] = "เอาออกจากทัวร์นาเมนต์",
        ["Tour.RemoveQ"] = "เอา \"{0}\" ออกจากทัวร์นาเมนต์นี้ใช่ไหม",
        ["Tour.RemoveStays"] = "ทีมยังอยู่ในทะเบียนเหมือนเดิม",
        ["Tour.Remove"] = "เอาออก",
        ["Tour.Removed"] = "เอาออกจากทัวร์นาเมนต์แล้ว",

        ["Tour.MatchSession"] = "สายการแข่ง",
        ["Tour.Played"] = "แข่งแล้ว {0} / {1}",
        ["Tour.MatchesDrawn"] = "จับสายแล้ว {0} คู่ เอาขึ้นจอได้จากตรงนี้เลย หรือเปิดสายการแข่งเพื่อกรอกคะแนน",
        ["Tour.NextMatches"] = "คู่ที่พร้อมแข่ง",
        ["Tour.NeedTwoTeams"] = "เพิ่มทีมอย่างน้อยสองทีม แล้วเปิดหน้าสายการแข่งเพื่อจับสาย",
        ["Tour.NoBracket"] = "ยังไม่ได้จับสาย เปิดหน้าสายการแข่งเพื่อจับ",
        ["Tour.OpenBracket"] = "เปิดสายการแข่ง",
        ["Tour.PickBanHistory"] = "ประวัติพิค/แบน",

        ["Tour.Standings"] = "ตารางคะแนน",
        ["Tour.PerGroup"] = "ผ่านเข้ารอบกลุ่มละ",
        ["Tour.DrawPlayoff"] = "จับสายรอบน็อกเอาต์",
        ["Tour.StandingsEmpty"] = "จับสายก่อน แล้วตารางจะเติมเองเมื่อผลทยอยเข้ามา",
        ["Tour.TiedHint"] = "แถวที่มี = คือเท่ากันทุกตัวชี้วัด ให้ตัดสินด้วยกติกาของรายการเองก่อนจับสาย",
        ["Tour.Table"] = "ตาราง",
        ["Tour.Group"] = "กลุ่ม {0}",
        ["Tour.StillToPlay"] = "ยังเหลืออีก {0} นัด",
        ["Tour.PlayoffTitle"] = "จับสายรอบน็อกเอาต์เลยไหม",
        ["Tour.PlayoffTop"] = "ทีมอันดับ 1 ถึง {0} ของแต่ละกลุ่มจะได้ไปเล่นรอบน็อกเอาต์",
        ["Tour.PlayoffSafe"] = "รอบแบ่งกลุ่มจะไม่ถูกแตะ จับสายซ้ำได้ แต่ทำได้เฉพาะตอนที่ยังไม่มีใครเล่นรอบน็อกเอาต์",
        ["Tour.Through"] = "ผ่านเข้ารอบ {0} ทีม",

        ["Tour.Details"] = "ข้อมูลทัวร์นาเมนต์",
        ["Tour.Name"] = "ชื่อ",
        ["Tour.Status"] = "สถานะ",
        ["Tour.Note"] = "โน้ต",
        ["Tour.SaveChanges"] = "บันทึก",
        ["Tour.Revert"] = "ย้อนกลับ",
        ["Tour.FormatTooSmall"] = "{0} รับได้ {1} ทีม ตอนนี้มี {2}",
        ["Tour.DeleteTournament"] = "ลบทัวร์นาเมนต์",
        ["Tour.DeleteTitle"] = "ลบทัวร์นาเมนต์",
        ["Tour.DeleteQ"] = "ลบ \"{0}\" ถาวรใช่ไหม",
        ["Tour.DeleteOnAir"] = "ตอนนี้กำลังออกอากาศอยู่ ลบแล้วแมตช์จะหลุดจากการถ่ายทอดทันที",
        ["Tour.DeleteErases"] = "รายชื่อทีม ทุกคู่ในสาย และดราฟต์ทุกชุดที่บันทึกไว้ใต้ทัวร์นาเมนต์นี้จะถูกลบทั้งหมด ย้อนกลับไม่ได้ และไม่เหลืออะไรไว้ให้กู้",
        ["Tour.DeleteTeamsStay"] = "ตัวทีมยังอยู่ในทะเบียน พร้อมประวัติในทัวร์นาเมนต์อื่นเหมือนเดิม",
        ["Tour.Deleted"] = "ลบ {0} แล้ว",
        ["Tour.DeletedCounts"] = " (หายไป {0} คู่ และดราฟต์ {1} ชุด)",

        ["Tour.ObsSources"] = "ลิงก์ OBS ของทัวร์นาเมนต์นี้",
        ["Tour.ObsHint"] = "ลิงก์ชุดนี้แสดงทัวร์นาเมนต์นี้เสมอ แม้อีกรายการจะออกอากาศอยู่ ลิงก์ที่เหลืออยู่ที่ปุ่มลิงก์ OBS บนแถบด้านบน",

        ["Teams.Title"] = "ทะเบียนทีม",
        ["Teams.New"] = "สร้างทีม",
        ["Teams.CreateTeam"] = "สร้างทีม",
        ["Teams.Count"] = "{0} ทีม",
        ["Teams.Shown"] = "แสดง {0}",
        ["Teams.Search"] = "ชื่อทีมหรือตัวย่อ",
        ["Teams.SelectAll"] = "เลือกทั้งหมดที่แสดงอยู่",
        ["Teams.Selected"] = "เลือกไว้ {0} ทีม",
        ["Teams.ClearSelection"] = "ล้างที่เลือก",
        ["Teams.DeleteSelected"] = "ลบที่เลือก ({0})",
        ["Teams.DeleteSelectedTitle"] = "ลบทีมที่เลือก",
        ["Teams.DeleteSelectedQ"] = "ลบทีมเหล่านี้ออกจากทะเบียนใช่ไหม ({0} ทีม)",
        ["Teams.DeleteSelectedDropped"] = "ทีมพวกนี้จะหลุดจากทุกทัวร์นาเมนต์ที่เคยลงแข่ง ส่วนประวัติการแข่งยังเก็บชื่อ ณ วันที่ลงเล่นไว้เหมือนเดิม",
        ["Teams.AndMore"] = " และอีก {0} ทีม",
        ["Teams.DeletedN"] = "ลบแล้ว {0} ทีม",
        ["Teams.Created"] = "สร้าง {0} แล้ว",
        ["Teams.InTournaments"] = "{0} ทัวร์นาเมนต์",
        ["Teams.InOneTournament"] = "1 ทัวร์นาเมนต์",
        ["Teams.Record"] = "ชนะ {0} – แพ้ {1}",
        ["Teams.Empty"] = "ยังไม่มีทีม สร้างที่นี่ หรือสร้างจากในทัวร์นาเมนต์ก็ได้",
        ["Teams.NoMatch"] = "ไม่มีทีมที่ตรงกับ \"{0}\"",
        ["Teams.Foot"] = "ทีมในทะเบียนใช้ร่วมกันทุกทัวร์นาเมนต์ แก้รายชื่อผู้เล่นแล้วมีผลทุกที่นับจากนี้ ส่วนแมตช์ที่แข่งไปแล้วยังเก็บรายชื่อตอนที่แข่งไว้",

        ["Profile.NotFound"] = "ไม่พบทีม",
        ["Profile.Captain"] = "กัปตัน: {0}",
        ["Profile.Games"] = "เกม {0} – {1}",
        ["Profile.NoMatchesYet"] = "ยังไม่เคยแข่ง",
        ["Profile.Edit"] = "รายชื่อผู้เล่นและโลโก้",
        ["Profile.Tournaments"] = "ทัวร์นาเมนต์",
        ["Profile.NoTournaments"] = "ทีมนี้ยังไม่ได้ถูกเพิ่มเข้าทัวร์นาเมนต์ไหนเลย",
        ["Profile.History"] = "ประวัติการแข่ง",
        ["Profile.HistoryHint"] = "แข่งแล้ว {0} นัด ล่าสุดอยู่บน",
        ["Profile.HistoryEmpty"] = "ยังไม่มีแมตช์ ต้องจับสายในทัวร์นาเมนต์ที่ทีมนี้ลงแข่งก่อน",
        ["Profile.Win"] = "ชนะ",
        ["Profile.Loss"] = "แพ้",
        ["Profile.Bye"] = "บาย",
        ["Profile.InProgress"] = "กำลังแข่ง",
        ["Profile.NotPlayed"] = "ยังไม่แข่ง",
        ["Profile.NoOpponent"] = "ไม่มีคู่แข่ง",
        ["Profile.Tbd"] = "ยังไม่รู้คู่แข่ง",
        ["Profile.UnknownTeam"] = "ไม่ทราบชื่อทีม",
        ["Profile.DeletedTeam"] = "ทีมที่ถูกลบ",
        ["Profile.Foot"] = "แก้รายชื่อผู้เล่นที่นี่มีผลนับจากนี้ แมตช์ที่แข่งไปแล้วยังเก็บผู้เล่นตอนที่แข่งไว้ ผลย้อนหลังและสถิติพิค/แบนจึงยังถูกต้อง",

        ["Settings.Backup"] = "สำรองข้อมูล",
        ["Backup.Hint"] = "ทุกอย่างในเครื่องนี้ (ทีม โลโก้ สาย และดราฟต์ทุกชุด) เก็บเป็นไฟล์เดียว เอาไปเก็บที่อื่นหรือย้ายไปเครื่องอื่นได้ ไฟล์สำรองจากเวอร์ชัน 2 ก็กู้คืนที่นี่ได้",
        ["Backup.Save"] = "บันทึกไฟล์สำรอง",
        ["Backup.RestoreButton"] = "กู้คืน…",
        ["Backup.Saved"] = "บันทึกไฟล์สำรองแล้ว: {0}",
        ["Backup.NotJson"] = "ไฟล์นี้อ่านเป็น JSON ไม่ได้",
        ["Backup.RestoreTitle"] = "กู้คืนจากไฟล์นี้ใช่ไหม",
        ["Backup.WillAdd"] = "จะเพิ่มเข้ามา {0} ทีม และ {1} ทัวร์นาเมนต์",
        ["Backup.Contents"] = "ในไฟล์ยังมี {0} คู่แข่ง ดราฟต์ {1} ชุด และโลโก้ {2} รูป สร้างเมื่อ {3}",
        ["Backup.AlreadyHere"] = "มีอยู่ในเครื่องแล้ว: {0} ทีม {1} ทัวร์นาเมนต์",
        ["Backup.MergeRule"] = "ของที่มีอยู่ในเครื่องแล้วจะไม่ถูกแตะ รายการที่ซ้ำจะถูกข้าม ไม่ใช่เขียนทับ",
        ["Backup.Restore"] = "กู้คืน",
        ["Backup.Restored"] = "กู้คืนแล้ว {0} ทีม และ {1} ทัวร์นาเมนต์"
    };
}
