namespace RovOverlay.Desktop.Services;

// The Statistics tab of a team's page.
public sealed partial class Loc
{
    private static readonly Dictionary<string, string> TeamStatsEn = new()
    {
        ["Profile.TabProfile"] = "Profile",
        ["Profile.TabStats"] = "Statistics",
        ["TStats.Scope"] = "Tournament",
        ["TStats.AllTournaments"] = "All tournaments",
        ["TStats.Based"] = "From {0} drafted games, {1} with a recorded winner",
        ["TStats.Series"] = "SERIES",
        ["TStats.Games"] = "GAMES",
        ["TStats.Blue"] = "ON BLUE SIDE",
        ["TStats.Red"] = "ON RED SIDE",
        ["TStats.Form"] = "LAST 5 SERIES",
        ["TStats.WinRate"] = "{0} won",
        ["TStats.NoResults"] = "no results yet",
        ["TStats.TournamentsCount"] = "in {0} tournaments",
        ["TStats.TournamentsOne"] = "in 1 tournament",
        ["TStats.W"] = "W",
        ["TStats.L"] = "L",
        ["TStats.NoForm"] = "No finished series yet",
        ["TStats.SidesUnknown"] = "{0} earlier games have no side recorded, so they are left out of the side records.",
        ["TStats.Picks"] = "HEROES PICKED",
        ["TStats.Bans"] = "BANNED BY THIS TEAM",
        ["TStats.BansAgainst"] = "BANNED AGAINST THIS TEAM",
        ["TStats.Hero"] = "HERO",
        ["TStats.Times"] = "GAMES",
        ["TStats.Rate"] = "RATE",
        ["TStats.Win"] = "WON",
        ["TStats.WinTip"] = "Won {0} of the {1} games with a recorded winner",
        ["TStats.NoWinner"] = "No game with this hero has a recorded winner yet",
        ["TStats.NoDrafts"] = "No drafted games yet.",
        ["TStats.Opponents"] = "RECORD VS EACH OPPONENT",
        ["TStats.Opponent"] = "OPPONENT",
        ["TStats.SeriesCol"] = "SERIES",
        ["TStats.GamesCol"] = "GAMES",
        ["TStats.Last"] = "LAST MEETING",
        ["TStats.LastText"] = "{0} · {1} – {2}",
        ["TStats.NoOpponents"] = "No opponent played yet.",
        ["TStats.Players"] = "PLAYER HERO POOLS",
        ["TStats.PlayerGames"] = "{0} games",
        ["TStats.PlayerHero"] = "×{0} · {1}",
        ["TStats.NoPlayers"] = "No player data yet. It counts drafts from version 3.0.13 on, using the player names on the Control Panel.",
        ["TStats.SidesNote"] = "Side records and player hero pools count drafts from version 3.0.13 on. Earlier games did not record which side a team played on screen or who sat in each row, so they are not guessed."
    };

    private static readonly Dictionary<string, string> TeamStatsTh = new()
    {
        ["Profile.TabProfile"] = "โปรไฟล์",
        ["Profile.TabStats"] = "สถิติ",
        ["TStats.Scope"] = "ทัวร์นาเมนต์",
        ["TStats.AllTournaments"] = "ทุกทัวร์นาเมนต์",
        ["TStats.Based"] = "จากดราฟต์ {0} เกม รู้ผลแพ้ชนะ {1} เกม",
        ["TStats.Series"] = "ซีรีส์",
        ["TStats.Games"] = "เกม",
        ["TStats.Blue"] = "ฝั่งน้ำเงิน",
        ["TStats.Red"] = "ฝั่งแดง",
        ["TStats.Form"] = "ซีรีส์ 5 คู่ล่าสุด",
        ["TStats.WinRate"] = "ชนะ {0}",
        ["TStats.NoResults"] = "ยังไม่มีผล",
        ["TStats.TournamentsCount"] = "ใน {0} ทัวร์นาเมนต์",
        ["TStats.TournamentsOne"] = "ใน 1 ทัวร์นาเมนต์",
        ["TStats.W"] = "ช",
        ["TStats.L"] = "พ",
        ["TStats.NoForm"] = "ยังไม่มีซีรีส์ที่จบ",
        ["TStats.SidesUnknown"] = "เกมก่อนหน้านี้ {0} เกม ไม่มีข้อมูลว่าเล่นฝั่งไหน จึงไม่ถูกนับในสถิติฝั่ง",
        ["TStats.Picks"] = "ฮีโร่ที่เลือก",
        ["TStats.Bans"] = "ฮีโร่ที่ทีมนี้แบน",
        ["TStats.BansAgainst"] = "ฮีโร่ที่โดนแบนใส่",
        ["TStats.Hero"] = "ฮีโร่",
        ["TStats.Times"] = "เกม",
        ["TStats.Rate"] = "อัตรา",
        ["TStats.Win"] = "ชนะ",
        ["TStats.WinTip"] = "ชนะ {0} จาก {1} เกมที่รู้ผล",
        ["TStats.NoWinner"] = "ยังไม่มีเกมที่ใช้ฮีโร่ตัวนี้แล้วรู้ผลแพ้ชนะ",
        ["TStats.NoDrafts"] = "ยังไม่มีเกมที่ดราฟต์ครบ",
        ["TStats.Opponents"] = "สถิติกับคู่แข่งแต่ละทีม",
        ["TStats.Opponent"] = "คู่แข่ง",
        ["TStats.SeriesCol"] = "ซีรีส์",
        ["TStats.GamesCol"] = "เกม",
        ["TStats.Last"] = "เจอกันล่าสุด",
        ["TStats.LastText"] = "{0} · {1} – {2}",
        ["TStats.NoOpponents"] = "ยังไม่เคยเจอคู่แข่ง",
        ["TStats.Players"] = "ฮีโร่ของผู้เล่นแต่ละคน",
        ["TStats.PlayerGames"] = "{0} เกม",
        ["TStats.PlayerHero"] = "×{0} · {1}",
        ["TStats.NoPlayers"] = "ยังไม่มีข้อมูลผู้เล่น นับจากดราฟต์ตั้งแต่เวอร์ชัน 3.0.13 โดยใช้ชื่อผู้เล่นในหน้าคุมงาน",
        ["TStats.SidesNote"] = "สถิติฝั่งและฮีโร่ของผู้เล่นแต่ละคน นับจากดราฟต์ตั้งแต่เวอร์ชัน 3.0.13 เกมก่อนหน้านั้นไม่ได้บันทึกว่าทีมเล่นฝั่งไหนบนจอ หรือใครนั่งแถวไหน จึงไม่เดาย้อนหลัง"
    };
}
