namespace RovOverlay.Desktop.Services;

// Design, Hotkeys and Guide strings.
public sealed partial class Loc
{
    private static readonly Dictionary<string, string> M5En = new()
    {
        ["Design.Title"] = "Design",
        ["Design.Preview"] = "Open live preview",
        ["Design.PreviewTip"] = "Opens the overlay in a browser window; colour changes show there as you make them",
        ["Design.Theme"] = "COLOURS AND SIZES",
        ["Design.ResetTheme"] = "Back to original",
        ["Design.ThemeReset"] = "Theme reset to original",
        ["Design.ThemeHint"] = "Changes reach every open overlay straight away, so judge them on the live preview rather than here.",
        ["Design.Blue"] = "Blue team",
        ["Design.Red"] = "Red team",
        ["Design.Text"] = "Text colour",
        ["Design.Accent"] = "Accent / urgent",
        ["Design.Label"] = "Label colour",
        ["Design.TypeTournament"] = "Tournament name",
        ["Design.TypeTitle"] = "Match title",
        ["Design.TypeScore"] = "Score",
        ["Design.TypeTimer"] = "Timer",
        ["Design.TypePlayer"] = "Player name",
        ["Design.TypeCaption"] = "Label size (BAN, phase, VS)",
        ["Design.LogoSize"] = "Logo size",
        ["Design.LogoInset"] = "Logo distance from centre",
        ["Design.Images"] = "BACKGROUND IMAGES",
        ["Design.UseImages"] = "Use these images",
        ["Design.ShowPanels"] = "Keep the built-in panels",
        ["Design.NoteBanner"] = "One strip holding bans, picks and the score",
        ["Design.NoteTop"] = "Result screen, top half: blue team",
        ["Design.NoteBottom"] = "Result screen, bottom half: red team",
        ["Design.NoImage"] = "No image yet",
        ["Design.Upload"] = "Upload",
        ["Design.Clear"] = "Clear",
        ["Design.Uploaded"] = "Image uploaded",
        ["Design.Cleared"] = "Image cleared",
        ["Design.TooBig"] = "Image must be 8 MB or smaller",
        ["Design.Foot"] = "Images are drawn behind everything else at exactly the size shown; anything larger is scaled down, anything smaller is stretched. They live with your data, not in the app folder.",

        ["Hotkeys.Local"] = "CONTROL PANEL KEYS",
        ["Hotkeys.LocalNote"] = "Work while this app has focus",
        ["Hotkeys.LocalHint"] = "Tapping a modifier on its own (Alt, Ctrl, Shift) is allowed and is the default for the banner toggle. It fires on release, and only when tapped alone, so Alt+Tab still switches windows without cutting your banner off air.",
        ["Hotkeys.Global"] = "SYSTEM-WIDE KEYS",
        ["Hotkeys.GlobalEnabled"] = "Switched on",
        ["Hotkeys.GlobalHint"] = "These keep working while OBS or the game has focus. They need Ctrl, Alt, Shift or Win, and Windows gives each one to whichever program asks first, so a key another program already holds is shown in red.",
        ["Hotkeys.ToggleBanner"] = "Show / hide overlay banner",
        ["Hotkeys.ToggleBannerNote"] = "Fades the banner off air and back",
        ["Hotkeys.PauseResume"] = "Pause / resume draft timer",
        ["Hotkeys.PrevPhase"] = "Previous draft phase",
        ["Hotkeys.NextPhase"] = "Next draft phase",
        ["Hotkeys.Undo"] = "Undo last pick or ban",
        ["Hotkeys.Change"] = "Change",
        ["Hotkeys.Default"] = "Default",
        ["Hotkeys.PressAKey"] = "Press a key…",
        ["Hotkeys.NotSet"] = "Not set",
        ["Hotkeys.Cancelled"] = "Cancelled",
        ["Hotkeys.NeedsModifier"] = "A system-wide hotkey needs Ctrl, Alt, Shift or Win",
        ["Hotkeys.RegisteredAs"] = "Registered as {0}",
        ["Hotkeys.TakenBy"] = "{0} — another program is holding this key",
        ["Hotkeys.CannotRegister"] = "This key cannot be registered system-wide",
        ["Hotkeys.ResetAll"] = "Reset all",
        ["Hotkeys.AllReset"] = "All hotkeys reset",
        ["Hotkeys.ResetGlobal"] = "Reset",
        ["Hotkeys.GlobalReset"] = "System-wide hotkeys reset",
        ["Hotkeys.GlobalOn"] = "System-wide hotkeys on",
        ["Hotkeys.GlobalOff"] = "System-wide hotkeys off",

        ["Guide.Search"] = "Search the guide",
        ["Guide.OpenWebTip"] = "Open the same guide as a web page",
        ["Guide.Missing"] = "The guide file could not be read. It ships with the app at backend\\docs\\USER_GUIDE.md."
    };

    private static readonly Dictionary<string, string> M5Th = new()
    {
        ["Design.Title"] = "ดีไซน์",
        ["Design.Preview"] = "เปิดตัวอย่างสด",
        ["Design.PreviewTip"] = "เปิดหน้า overlay ในเบราว์เซอร์ ปรับสีแล้วเห็นผลที่นั่นทันที",
        ["Design.Theme"] = "สีและขนาด",
        ["Design.ResetTheme"] = "กลับเป็นค่าเดิม",
        ["Design.ThemeReset"] = "คืนค่าธีมเป็นค่าเดิมแล้ว",
        ["Design.ThemeHint"] = "ค่าที่ปรับถึงทุกหน้า overlay ที่เปิดอยู่ทันที ให้ตัดสินจากตัวอย่างสด ไม่ใช่จากหน้านี้",
        ["Design.Blue"] = "ทีมน้ำเงิน",
        ["Design.Red"] = "ทีมแดง",
        ["Design.Text"] = "สีตัวอักษร",
        ["Design.Accent"] = "สีเน้น / ใกล้หมดเวลา",
        ["Design.Label"] = "สีป้ายกำกับ",
        ["Design.TypeTournament"] = "ชื่อทัวร์นาเมนต์",
        ["Design.TypeTitle"] = "ชื่อแมตช์",
        ["Design.TypeScore"] = "คะแนน",
        ["Design.TypeTimer"] = "นาฬิกา",
        ["Design.TypePlayer"] = "ชื่อผู้เล่น",
        ["Design.TypeCaption"] = "ขนาดป้ายกำกับ (BAN, เฟส, VS)",
        ["Design.LogoSize"] = "ขนาดโลโก้",
        ["Design.LogoInset"] = "ระยะโลโก้จากกึ่งกลาง",
        ["Design.Images"] = "ภาพพื้นหลัง",
        ["Design.UseImages"] = "ใช้ภาพชุดนี้",
        ["Design.ShowPanels"] = "คงกรอบเดิมของแอปไว้",
        ["Design.NoteBanner"] = "แถบเดียวรวมแบน พิค และคะแนน",
        ["Design.NoteTop"] = "หน้าผล ครึ่งบน: ทีมน้ำเงิน",
        ["Design.NoteBottom"] = "หน้าผล ครึ่งล่าง: ทีมแดง",
        ["Design.NoImage"] = "ยังไม่มีภาพ",
        ["Design.Upload"] = "อัปโหลด",
        ["Design.Clear"] = "ลบภาพ",
        ["Design.Uploaded"] = "อัปโหลดภาพแล้ว",
        ["Design.Cleared"] = "ลบภาพแล้ว",
        ["Design.TooBig"] = "ภาพต้องไม่เกิน 8 MB",
        ["Design.Foot"] = "ภาพถูกวาดไว้ใต้ทุกอย่างตามขนาดที่ระบุพอดี ใหญ่กว่านั้นจะถูกย่อ เล็กกว่านั้นจะถูกยืด ไฟล์เก็บไว้กับข้อมูลของคุณ ไม่ได้อยู่ในโฟลเดอร์โปรแกรม",

        ["Hotkeys.Local"] = "คีย์ลัดหน้าคุมงาน",
        ["Hotkeys.LocalNote"] = "ใช้ได้ตอนที่แอปนี้อยู่หน้าสุด",
        ["Hotkeys.LocalHint"] = "แตะปุ่ม modifier เดี่ยวๆ (Alt, Ctrl, Shift) ได้ และเป็นค่าเริ่มต้นของปุ่มเปิด/ปิดแบนเนอร์ มันทำงานตอนปล่อยปุ่ม และเฉพาะตอนที่แตะปุ่มนั้นปุ่มเดียว Alt+Tab จึงยังสลับหน้าต่างได้โดยแบนเนอร์ไม่ดับ",
        ["Hotkeys.Global"] = "คีย์ลัดระดับระบบ",
        ["Hotkeys.GlobalEnabled"] = "เปิดใช้งาน",
        ["Hotkeys.GlobalHint"] = "ชุดนี้ทำงานแม้ OBS หรือเกมจะอยู่หน้าสุด ต้องมี Ctrl, Alt, Shift หรือ Win ประกอบ และ Windows ให้สิทธิ์โปรแกรมที่ขอก่อน ปุ่มที่โปรแกรมอื่นจองไว้แล้วจะขึ้นสีแดง",
        ["Hotkeys.ToggleBanner"] = "แสดง / ซ่อนแบนเนอร์",
        ["Hotkeys.ToggleBannerNote"] = "ค่อยๆ จางแบนเนอร์ออกจากจอแล้วเรียกกลับมา",
        ["Hotkeys.PauseResume"] = "พัก / เดินนาฬิกาดราฟต์ต่อ",
        ["Hotkeys.PrevPhase"] = "เฟสดราฟต์ก่อนหน้า",
        ["Hotkeys.NextPhase"] = "เฟสดราฟต์ถัดไป",
        ["Hotkeys.Undo"] = "ย้อนพิคหรือแบนล่าสุด",
        ["Hotkeys.Change"] = "เปลี่ยน",
        ["Hotkeys.Default"] = "ค่าเริ่มต้น",
        ["Hotkeys.PressAKey"] = "กดปุ่มที่ต้องการ…",
        ["Hotkeys.NotSet"] = "ยังไม่ได้ตั้ง",
        ["Hotkeys.Cancelled"] = "ยกเลิกแล้ว",
        ["Hotkeys.NeedsModifier"] = "คีย์ลัดระดับระบบต้องมี Ctrl, Alt, Shift หรือ Win ประกอบ",
        ["Hotkeys.RegisteredAs"] = "จองไว้เป็น {0}",
        ["Hotkeys.TakenBy"] = "{0} — โปรแกรมอื่นจองปุ่มนี้อยู่",
        ["Hotkeys.CannotRegister"] = "ปุ่มนี้จองระดับระบบไม่ได้",
        ["Hotkeys.ResetAll"] = "คืนค่าทั้งหมด",
        ["Hotkeys.AllReset"] = "คืนค่าคีย์ลัดทั้งหมดแล้ว",
        ["Hotkeys.ResetGlobal"] = "คืนค่า",
        ["Hotkeys.GlobalReset"] = "คืนค่าคีย์ลัดระดับระบบแล้ว",
        ["Hotkeys.GlobalOn"] = "เปิดคีย์ลัดระดับระบบแล้ว",
        ["Hotkeys.GlobalOff"] = "ปิดคีย์ลัดระดับระบบแล้ว",

        ["Guide.Search"] = "ค้นหาในคู่มือ",
        ["Guide.OpenWebTip"] = "เปิดคู่มือชุดเดียวกันแบบหน้าเว็บ",
        ["Guide.Missing"] = "อ่านไฟล์คู่มือไม่ได้ ไฟล์นี้มากับโปรแกรมที่ backend\\docs\\USER_GUIDE.md"
    };
}
